version: "3.9"
services:
  # frontend:
  #   build: ./client
  #   restart: always
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend
  backend:
    build: ./server
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    # volumes:
    #   - ./server/src:/app/src
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digimon
    ports:
      - "5432:5432"
    # volumes:
    #   - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
